###########################
#### SECURITY SETTINGS ####
###########################
security:
  jwt:
    secret-key: wC0kL2XCJEbYITs2qJEBjA8NRFB3A54zh6EXMWvc6gCvY125VhR2aTf2FqxfJ1F26xWaPniR2mVh5nBpIlgDSdposd546SDgsdgSRDF35SDgjs4dsgsd542rtefSDGShfdh
    issuer: The Rebel Alliance
    expiration-in-ms: 14400000
  role-with-registration: ROLE_USER